Strong cast environment variables to type string
If an environment variable is added to the config, which is just a number, it is decoded from YAML into an int which causes a botocore.exceptions.ParamValidationError

Here is the relevant part of the stack trace:

botocore/validate.py", line 291, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter Environment.Variables.lowThreshold, value: 5, type: <class 'int'>, valid types: <class 'str'>